name: Tests
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: |
          make install
      - name: Setup
        run: |
          make setup
      - name: build
        run: |
          make build    
      - name: Start project
        run: |
          make start
      - name: Tests
        run: |
          make test
      - name: Linter
        run: |
          make lint
